
1:  
SELECT E.FIRST_NAME, E.LAST_NAME, H.EMPLOYEE_ID, COUNT(*) as cant
FROM HR.JOB_HISTORY H JOIN HR.EMPLOYEES E 
ON H.EMPLOYEE_ID = E.EMPLOYEE_ID 
GROUP BY 
E.FIRST_NAME, E.LAST_NAME, H.EMPLOYEE_ID 
HAVING COUNT (*) > 1; 

2: 
SELECT CONCAT (E.FIRST_NAME, ' ', E.LAST_NAME) AS NAME, C.COUNTRY_NAME AS COUNTRY, E.SALARY 
FROM HR.EMPLOYEES E 
JOIN HR.DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN HR.LOCATIONS L ON L.LOCATION_ID = D.LOCATION_ID 
JOIN HR.COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID 
JOIN HR.REGIONS R ON C.REGION_ID = R.REGION_ID 
WHERE R.REGION_ID = 10 AND E.SALARY BETWEEN 4000 AND 6000 

 
3:
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLEADO,
    '******' || SUBSTR(E.EMAIL, 1, 3) EMAIL_EMPLEADO, M.FIRST_NAME || ' ' || M.LAST_NAME JEFE,
    '******' || SUBSTR(M.EMAIL, 1, 3) EMAIL_JEFE
FROM HR.EMPLOYEES E
LEFT JOIN HR.EMPLOYEES M ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY E.LAST_NAME;

4: 
 CREATE TABLE EMPLOYEES_2 AS SELECT * FROM HR.EMPLOYEES; 

 

 